server:
  port: 8080
spring:
  application:
    name: order-service

  #nacos连接配置
  cloud:
    nacos:
      server-addr: localhost:8848

  datasource:
    url: jdbc:mysql://localhost:3306/cloud_order?useSSL=false
    username: root
    password: mysql0925
#    password: 123456rsb
    driver-class-name: com.mysql.jdbc.Driver

#erueka连接配置
#eureka:
#  client:
#    service-url:
#      defaultZone: http://127.0.0.1:10086/eureka
      

mybatis:
  type-aliases-package: com.ransibi.user.pojo
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    cn.itcast: debug
  pattern:
    dateformat: MM-dd HH:mm:ss:SSS